fn main() -> Result<(), std::io::Error> {
    println!("task 2");

    Ok(())
}